[MM-30353] Cypress/E2E: Automate backlogs - Plugins > Demo plgin functionality pt. 3 (4 test case)
mattermost/mattermost-plugin-demo pull request #131
Opened 2020-12-04 17:06 UTC by jfrerich

#### Summary
E2E testing for https://mattermost.atlassian.net/browse/MM-30353

**NOTE** this PR commit is based off https://github.com/mattermost/mattermost-plugin-demo/tree/MM-30351 and https://github.com/mattermost/mattermost-plugin-demo/pull/130
Many of the changes in this commit will disappear once that PR is merged to master.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30353

2020-12-14 09:50 UTC, hanzei requested changes
I don't see a test case for MM-T3416. Is that intended?

2020-12-14 09:50 UTC, hanzei commented on e2e/cypress/integration/post_menu_spec.ts
> +
Nit: Remove empty line

2020-12-14 09:50 UTC, hanzei commented on e2e/cypress/integration/demo_channel_spec.ts
> +      })
Nit pick: Missing semicolon

2020-12-14 09:50 UTC, hanzei commented on e2e/cypress/integration/demo_channel_spec.ts
> +        cy.get(`#post_${postId}`).should('contain', 'You must not talk about the demo plugin user')
`contain` or `have.text`?

2020-12-14 09:51 UTC, hanzei commented
@jfrerich It a bit hard to spot the diff between https://github.com/mattermost/mattermost-plugin-demo/pull/130 and this PR. Could you please link it?

2021-01-05 15:39 UTC, saturninoabril commented
Thanks Jason! I'll wait for https://github.com/mattermost/mattermost-plugin-demo/pull/130 to get merged before reviewing this PR.

2024-04-15 16:25 UTC, closed without merging