Add user settings registry
mattermost/mattermost-plugin-demo pull request #172
Opened 2023-12-04 13:57 UTC by larkox

#### Summary
Add user settings functionality to the demo plugin

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55755

2023-12-04 13:59 UTC, larkox commented on webapp/package.json
For some reason I wasn't able to build the webapp part of the plugin, so I took the liberty to bump the dependencies.

2023-12-04 21:37 UTC, marianunez requested changes
Can we add the documentation in the webapp Readme of how this new registry would look like?  here -> https://github.com/mattermost/mattermost-plugin-demo/tree/master/webapp#main-menu-action

2023-12-05 15:28 UTC, marianunez approved these changes
Thanks @larkox! Do we need to bump the min server version for support of this new registry? https://github.com/mattermost/mattermost-plugin-demo/blob/308bdd639fb46a97ab0487a69bf4260b6ae16127/plugin.json#L9C6-L9C24

2023-12-13 15:59 UTC, larkox commented
@marianunez Not really. The code checks whether the registry exist, and use it if it exist, and doesn't use it if not. Therefore... the plugin can work with previous versions (it won't show the settings, thought).

2023-12-14 09:30 UTC, yasserfaraazkhan approved these changes
able to save options
<img width="500" alt="image" src="https://github.com/mattermost/mattermost-plugin-demo/assets/15979783/25f4d077-9984-41db-898e-f39327f8b596">

2023-12-19 12:32 UTC, larkox commented
/update-branch

2023-12-19 12:41 UTC, merged